FROM intel/oneapi-hpckit:devel-ubuntu18.04
SHELL ["/bin/bash", "-l", "-c"]


ENV SOFT /home/soft
RUN mkdir -p $SOFT/udpPacketManager/

ARG BUILD_CORES=8
ARG OPT_ARCH="native"
ARG DEBIAN_FRONTEND=noninteractive
COPY . $SOFT/udpPacketManager/
RUN find $SOFT/udpPacketManager/ && touch $SOFT/$BUILD_COMMIT


# Get the latest version of in-active-development software
# This arg is updated at build time by the makefile and will cause
# the remainder of this dockerfile to recompile every time it is run
# on a new day

WORKDIR /home/soft


# Build and install udpPacketManager/mockHeader, riptide, PSRSalsa, CDMT, IQRM, PSRDADA-python
WORKDIR $SOFT/udpPacketManager
RUN echo "Building udpPacketManager" && \
	\
	apt-get update && \
	apt-get install -y autoconf csh curl fftw3-dev git locate libtool wget libzstd-dev && \
	updatedb && ldconfig && \
	python3 -m pip install --force git+https://github.com/David-McKenna/sigpyproc3.git@medianDownsample && \
	curl https://gist.githubusercontent.com/David-McKenna/0200de78fb4d8f99957e87a3b5654e19/raw/e411b06ba23f77f61bf8d58f49e95798e96232f6/sigproc_downsample.py -o /usr/local/bin/sigproc_downsample.py && \
	chmod +x /usr/local/bin/sigproc_downsample.py && \
	CC=icc CXX=icpc make mockHeader all install -j8 > /dev/null && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /home/user
ENTRYPOINT /bin/bash

