on:
  push:
  pull_request:


jobs:

  build_container:
    name: Docker Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Build Step
        run: docker build . --file src/docker/Dockerfile