on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'build*.sh'


jobs:

  build_container:
    name: Docker Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Build Step
        run: docker build . --file src/docker/Dockerfile